'use strict';
const STORAGE='awsStudyGuide.progress.v1';
const state={data:null,view:'home',activeChapter:'it',activeLesson:null,practiceIndex:0,practiceScore:0,practiceAnswered:false,progress:loadProgress()};
const $=id=>document.getElementById(id); const $$=q=>[...document.querySelectorAll(q)];
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
function emptyProgress(){return{schemaVersion:1,completed:[],weak:[],bookmarks:[],quizHistory:{},updatedAt:null,lessonDone:[],lessonChecks:{},confidence:{},scenarioHistory:{}}}
function loadProgress(){try{const p=JSON.parse(localStorage.getItem(STORAGE)||'null');return p&&p.schemaVersion===1?{...emptyProgress(),...p,lessonDone:Array.isArray(p.lessonDone)?p.lessonDone:[],lessonChecks:p.lessonChecks||{},confidence:p.confidence||{},scenarioHistory:p.scenarioHistory||{}}:emptyProgress()}catch{return emptyProgress()}}
function save(){state.progress.updatedAt=new Date().toISOString();try{localStorage.setItem(STORAGE,JSON.stringify(state.progress));return true}catch(e){toast('学習データを保存できませんでした');return false}}
async function init(){bind();try{const paths=['./data/course-core.json','./data/lessons-foundation.json','./data/lessons-core-services.json','./data/lessons-advanced.json'];const docs=await Promise.all(paths.map(async p=>{const r=await fetch(p,{cache:'no-store'});if(!r.ok)throw Error(`${p} HTTP ${r.status}`);return r.json()}));state.data={...docs[0],lessons:[...docs[1].lessons,...docs[2].lessons,...docs[3].lessons]};migrateLegacy();$('datasetStatus').textContent=`Course ${state.data.version}`;renderAll()}catch(e){console.error(e);$('datasetStatus').textContent='教材読込エラー';toast('教材を読み込めませんでした')}}
function bind(){document.addEventListener('click',e=>{const nav=e.target.closest('[data-nav]');if(nav){e.preventDefault();switchView(nav.dataset.nav)}const open=e.target.closest('[data-open-lesson]');if(open)openLesson(open.dataset.openLesson)});$('menuBtn').addEventListener('click',()=>{const open=document.body.classList.toggle('menu-open');$('menuBtn').setAttribute('aria-expanded',String(open))});document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement!==$('searchInput')){e.preventDefault();$('searchInput').focus()}if(e.key==='Escape'){document.body.classList.remove('menu-open');$('menuBtn').setAttribute('aria-expanded','false')}});$('searchInput').addEventListener('input',globalSearch);$('glossarySearch').addEventListener('input',renderGlossary);$('backupBtn').addEventListener('click',exportBackup);$('completeLesson').addEventListener('click',completeAndNext);$('prevLesson').addEventListener('click',prevLesson)}
function migrateLegacy(){let changed=false;for(const l of state.data.lessons){if(l.legacyTopicId&&state.progress.completed.includes(l.legacyTopicId)&&!state.progress.lessonDone.includes(l.id)){state.progress.lessonDone.push(l.id);changed=true}}if(changed)save()}
function renderAll(){renderProgress();renderHome();renderCourse();renderMap();renderCompare();renderPractice();renderReview();renderGlossary();switchView('home')}
function switchView(view){if(!document.querySelector(`[data-view="${view}"]`))return;state.view=view;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));document.body.classList.remove('menu-open');$('menuBtn').setAttribute('aria-expanded','false');const labels={home:['START HERE','学習ホーム'],course:['LEARNING PATH','学習コース'],lesson:['LESSON','Lesson'],map:['ARCHITECTURE','AWS構成マップ'],compare:['COMPARE','使い分け'],practice:['PRACTICE','構成問題'],review:['REVIEW','復習'],glossary:['REFERENCE','用語辞書']};$('viewEyebrow').textContent=labels[view]?.[0]||'';$('viewMini').textContent=labels[view]?.[1]||'';window.scrollTo({top:0,behavior:'smooth'})}
function completedSet(){return new Set(state.progress.lessonDone.filter(id=>state.data.lessons.some(l=>l.id===id)))}
function renderProgress(){if(!state.data)return;const done=completedSet().size,total=state.data.lessons.length,pct=Math.round(done/total*100);$('railPercent').textContent=`${pct}%`;$('railBar').style.width=`${pct}%`;$('railMeta').textContent=`${done} / ${total} Lessons`;$('coursePercent').textContent=`${pct}%`;const wrong=Object.values(state.progress.lessonChecks).filter(x=>x&&x.correct===false).length;const checks=Object.values(state.progress.lessonChecks);const correct=checks.filter(x=>x.correct).length;$('statDone').textContent=`${done} / ${total}`;$('statReview').textContent=String(getReviewLessons().length);$('statChecks').textContent=checks.length?`${Math.round(correct/checks.length*100)}%`:'—';const mins=state.data.lessons.filter(l=>!completedSet().has(l.id)).reduce((a,l)=>a+l.minutes,0);$('statMinutes').textContent=mins?`${mins}分`:'完了'}
function getNextLesson(){return state.data?.lessons.find(l=>!completedSet().has(l.id))||null}
function renderHome(){const next=getNextLesson();if(next){const ch=chapter(next.chapter);$('todayReason').textContent=completedSet().size?'前回の続きから進めます':'完全初心者はここから開始';$('todayTitle').textContent=next.title;$('todayDesc').textContent=`${ch.title} ・ 約${next.minutes}分 — ${next.lead}`;$('todayStart').textContent='ここから続ける';$('todayStart').onclick=()=>openLesson(next.id)}else{$('todayReason').textContent='基礎コースを完走しました';$('todayTitle').textContent='次は復習と構成問題で定着';$('todayDesc').textContent='確認問題で間違えたLessonや曖昧なLessonを復習し、要件からAWSサービスを選ぶ練習へ進みます。';$('todayStart').textContent='復習へ進む';$('todayStart').onclick=()=>switchView('review')}const host=$('homeChapters');host.innerHTML=state.data.chapters.slice(0,6).map((c,i)=>{const ls=lessonsIn(c.id),done=ls.filter(l=>completedSet().has(l.id)).length;return `<button class="chapter-card" data-home-chapter="${c.id}"><span>${c.accent}</span><strong>${esc(c.title)}</strong><small>${done}/${ls.length} Lesson 完了</small></button>`}).join('');host.querySelectorAll('[data-home-chapter]').forEach(b=>b.addEventListener('click',()=>{state.activeChapter=b.dataset.homeChapter;renderCourse();switchView('course')}))}
